用户指南
------------

这部分文档会展示如何在 Flask 中开始使用 Flask-SQLALchemy 。

.. toctree::
   :maxdepth: 2

   quickstart
   contexts
   config
   models
   queries
   binds
   signals

API 参考
-------------

如果你在寻找一个特定函数、类或方法的信息，那么这部分文档就是给你准备的。

.. toctree::
   :maxdepth: 2

   api

额外说明
----------------

参阅 Flask 的 license_ 获取支配这个项目的法律信息

.. toctree::
   :maxdepth: 2

   changelog
   glossary

.. _license: http://flask.pocoo.org/docs/license/
